mrsun/urls.py
from django.contrib import admin
from django.urls import path
from sun.views import (home, add_products, add_customers, add_booking_page, add_booking_row, get_amt_for_booking,
                       add_sales_page, get_amt_for_sales,add_sale_row,
                       gen_pdf_for_sales, gen_pdf_for_booking, add_expense,
                       add_employess, all_acc, transfer_debt_from_com_to_babak_page,babak_debit,
                       add_amount_account_page,debt_ledger, add_amount_account_page_com,
                       own_debt_ledger,
                       all_stock_report, todays_sale_report, shop_exp_report_all,shop_exp_report,
                       fetch_all_sales_report, all_sales_report,
                       find_debt_recipt_for_debt, search_page_debt_bill, debt_recipt_for_debt,                                         search_page_pay_bill, find_payment_recipt,payment_recipt,
                       add_pur,add_parts,add_mani_pro, add_sales_return_page, gen_pdf_for_sales_return, add_account,give_sal_to_emp, salary_details, add_pur_row, gen_pdf_for_pur, fetch_all_pur_report,
                       search_pur_bill)

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', home, name='hom'),




    path('add_pro/', add_products, name='adpro'),
    path('add_cust/', add_customers, name='adcust'),

    path('add_booking/', add_booking_page, name='adbk'),
    path('booking_invoice/', gen_pdf_for_booking, name='bookinginvoice'),
    path('add_new_booking_row/', add_booking_row, name='adbkrw'),
    path('amt_for_booking/<str:name>/', get_amt_for_booking, name='amtfbk'),

    path('add/sale/', add_sales_page, name='adsal'),
    path('sales_invoice/', gen_pdf_for_sales, name='saleinvoice'),
    path('amt_for_sale/<str:name>/', get_amt_for_sales, name='amtfsale'),
    path('add_new_sale_row/', add_sale_row, name='adbkrw'),

    # Add Expense
    path('add_expensess/', add_expense, name='adexp'),
    # Add Employees
    path('add_emp/', add_employess, name='addemp'),
    # All Accounts
    path('accounts/', all_acc, name='allacc'),

    #------------------babak transfer_debit page----------------------
    path('transfer_debit/', transfer_debt_from_com_to_babak_page , name='transdebpage'),
    #-------------------Babak Debit Ledger----------------------------
    path('my_debit_ledger/', babak_debit , name='bakleg'),

    # -------------- Debt Receive Update Accounts ------------------------------
    path('add_amount_page/', add_amount_account_page , name='adamtpg'),

    #-----------------debt Receive ledger--------------------------
    path('acc_ledger/', debt_ledger , name='leg'),

    # -------------- Own Debt Paying to Companies ledg ------------------------------

    path('paid_debt_ledger/', own_debt_ledger , name='paiddetail'),
    # -------------- Paying to com Update Accounts ------------------------------
    path('add_amount_page_com/', add_amount_account_page_com , name='adpycom'),

    #-----------------Reports--------------------------------------

    #-----------------all Products---------------------------------
    path('allproducts/', all_stock_report, name='alsr'),

    #---------------- Todays Sale & Stock Product Report
    path('todaysreport/', todays_sale_report, name='tdr'),

    #------------Todays Shop Exp Report and per exp report--------
    path('todays_s_exp_rep/', shop_exp_report , name='shopexpreport'),
    path('shop_all_exp/', shop_exp_report_all , name='shopexpreportall'),

    # --------- Bill Reports ------------------------------------
    path('bill/', fetch_all_sales_report, name='als'),
    path('bills/<int:id>/', all_sales_report , name='alsbil'),

    #-----------------debit Receive Invoice for--------------------------------
    path('debit_rep/', debt_recipt_for_debt , name='debtrep'),
    path('search/debt_bill/', search_page_debt_bill , name='sdb'),
    path('debit_rep/<int:id>/', find_debt_recipt_for_debt , name='debtrep'),

    #------------------ Find Payment Bill-------------------------------------
    path('payment_rep/', payment_recipt , name='payrep'),
    path('search/payment_rep/',search_page_pay_bill  , name='spb'),
    path('payment_rep/<int:id>/', find_payment_recipt , name='payrep'),


    path('add_purchase/', add_pur , name='addpur'),
    path('add_parts/', add_parts , name='addprts'),
    path('add_manipro/', add_mani_pro , name='addpani'),

    path('add/sale_return/', add_sales_return_page, name='salereutrn'),
    path('sales_invoice_return/', gen_pdf_for_sales_return, name='saleinvoicereturn'),

    path('edit_acc/<int:id>/', add_account, name='adacc'),

    path('give_salary/', give_sal_to_emp, name='gvsal'),
    path('salary_details/', salary_details, name='saldetailsemp'),

    path('add_new_pur_row/', add_pur_row , name='adpurrow'),
    path('pur_invoice/', gen_pdf_for_pur, name='purinvoicereturn'),

    path('pur_bill/', fetch_all_pur_report, name='allpurbill'),
    path('s_pur_bills/<int:id>/', search_pur_bill , name='spurbill'),
]

sun/models.py
from django.db import models


class Accounts(models.Model):
    accounts_id = models.AutoField(primary_key=True)
    accounts_name = models.CharField(max_length=45, blank=True, null=True)
    credit = models.FloatField(blank=True, null=True)
    debit = models.FloatField(blank=True, null=True)
    bal = models.FloatField(blank=True, null=True)
    customers_cust = models.ForeignKey('Customers', models.DO_NOTHING)
    var = models.FloatField(blank=True, null=True)
    bkvar = models.FloatField(blank=True, null=True)
    opn_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return str(self.accounts_name)


    class Meta:
        managed = False
        db_table = 'Accounts'
        unique_together = (('accounts_id', 'customers_cust'),)


class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True)
    cust_name = models.CharField(max_length=45, blank=True, null=True)
    dat = models.DateField(blank=True, null=True)

    def __str__(self):
        return str(self.cust_name)


    class Meta:
        managed = False
        db_table = 'booking'


class BookingDetails(models.Model):
    booking_details_id = models.AutoField(primary_key=True)
    pro_name = models.CharField(max_length=55, blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    amt = models.FloatField(blank=True, null=True)
    discount = models.FloatField(blank=True, null=True)
    booking_booking = models.ForeignKey(Booking, models.DO_NOTHING)
    ecode = models.CharField(max_length=45, blank=True, null=True)
    total = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'booking_details'
        unique_together = (('booking_details_id', 'booking_booking'),)


class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'category'


class Customers(models.Model):
    cust_id = models.AutoField(primary_key=True)
    cust_name = models.CharField(max_length=45, blank=True, null=True)
    city = models.CharField(max_length=45, blank=True, null=True)
    contact_no = models.CharField(max_length=45, blank=True, null=True)
    dat = models.DateField(blank=True, null=True)

    def __str__(self):
        return str(self.cust_name)

    class Meta:
        managed = False
        db_table = 'customers'


class Exp(models.Model):
    exp_id = models.AutoField(primary_key=True)
    amt = models.FloatField(blank=True, null=True)
    dat = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'exp'


class ExpDetails(models.Model):
    exp_details_id = models.AutoField(primary_key=True)
    desc = models.CharField(max_length=45, blank=True, null=True)
    amt = models.FloatField(blank=True, null=True)
    exp_exp = models.ForeignKey(Exp, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'exp_details'
        unique_together = (('exp_details_id', 'exp_exp'),)


class Products(models.Model):
    products_id = models.AutoField(db_column='Products_id', primary_key=True)  # Field name made lowercase.
    name = models.CharField(max_length=45, blank=True, null=True)
    p_p = models.FloatField(blank=True, null=True)
    r_p = models.FloatField(blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    e_code = models.CharField(max_length=45, blank=True, null=True)
    dt = models.DateField(blank=True, null=True)

    def __str__(self):
        return str(self.name)


    class Meta:
        managed = False
        db_table = 'products'



class Purchase(models.Model):
    purchase_id = models.AutoField(primary_key=True)
    com_name = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'purchase'


class PurchaseDetails(models.Model):
    purchase_details_id = models.AutoField(primary_key=True)
    pro_name = models.CharField(max_length=55, blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    p_p = models.FloatField(blank=True, null=True)
    r_p = models.FloatField(blank=True, null=True)
    dat = models.DateField(blank=True, null=True)
    purchase_purchase = models.ForeignKey(Purchase, models.DO_NOTHING)
    total = models.FloatField(blank=True, null=True)
    ec = models.CharField(max_length=45, blank=True, null=True)
    dis = models.FloatField(blank=True, null=True)




    class Meta:
        managed = False
        db_table = 'purchase_details'
        unique_together = (('purchase_details_id', 'purchase_purchase'),)


class Sales(models.Model):
    sales_id = models.AutoField(primary_key=True)
    cust_name = models.CharField(max_length=45, blank=True, null=True)
    dat = models.DateField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    net_total = models.FloatField(blank=True, null=True)
    paid = models.FloatField(blank=True, null=True)
    due = models.FloatField(blank=True, null=True)

    def __str__(self):
        return str(self.sales_id )

    class Meta:
        managed = False
        db_table = 'sales'


class SalesDetails(models.Model):
    sales_details_id = models.AutoField(primary_key=True)
    pro_name = models.CharField(max_length=55, blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    dat = models.DateField(blank=True, null=True)
    sales_sales = models.ForeignKey(Sales, models.DO_NOTHING)
    dis = models.FloatField(blank=True, null=True)
    ecode = models.CharField(max_length=45, blank=True, null=True)


    class Meta:
        managed = False
        db_table = 'sales_details'
        unique_together = (('sales_details_id', 'sales_sales'),)


class Stock(models.Model):
    stock_id = models.AutoField(primary_key=True)
    com_name = models.CharField(max_length=45, blank=True, null=True)
    bilno = models.IntegerField(blank=True, null=True)
    no_of_pro = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.stock_id)

    class Meta:
        managed = False
        db_table = 'stock'


class StockDetails(models.Model):
    stock_details_id = models.AutoField(primary_key=True)
    pro_name = models.CharField(max_length=55, blank=True, null=True)
    p_p = models.FloatField(blank=True, null=True)
    r_p = models.FloatField(blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    dat = models.DateField(blank=True, null=True)
    stock_stock = models.ForeignKey(Stock, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'stock_details'
        unique_together = (('stock_details_id', 'stock_stock'),)


class ProVdPpPr(models.Model):
    pro_id = models.AutoField(primary_key=True)
    p_name = models.CharField(max_length=45, blank=True, null=True)
    p_pp = models.FloatField(blank=True, null=True)
    p_rp = models.FloatField(blank=True, null=True)
    saled_price = models.FloatField(blank=True, null=True)
    dat = models.DateField(blank=True, null=True)
    total = models.FloatField(blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    sal_id = models.IntegerField(blank=True, null=True)
    profit = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pro_vd_pp_pr'

class AccountsLedger(models.Model):
    accounts_ledger_id = models.AutoField(primary_key=True)
    given_from = models.CharField(max_length=45, blank=True, null=True)
    given_to = models.CharField(max_length=45, blank=True, null=True)
    desc = models.CharField(db_column='Desc', max_length=45, blank=True, null=True)  # Field name made lowercase.
    amount = models.FloatField(blank=True, null=True)
    dat = models.DateField(blank=True, null=True)
    accounts_accounts = models.ForeignKey('Accounts', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'accounts_ledger'
        unique_together = (('accounts_ledger_id', 'accounts_accounts'),)


class Employees(models.Model):
    employees_id = models.AutoField(primary_key=True)
    employees_name = models.CharField(max_length=45, blank=True, null=True)
    employees_job_title = models.CharField(max_length=45, blank=True, null=True)
    employees_salary = models.IntegerField(blank=True, null=True)
    employees_status = models.CharField(max_length=45, blank=True, null=True)


    def __str__(self):
        return str(self.employees_name)

    class Meta:
        managed = False
        db_table = 'employees'


class EmpAccounts(models.Model):
    emp_accounts_id = models.AutoField(primary_key=True)
    emp_account_name = models.CharField(max_length=45, blank=True, null=True)
    emp_accounts_credit = models.FloatField(blank=True, null=True)
    emp_accounts_debit = models.FloatField(blank=True, null=True)
    dat = models.DateField(blank=True, null=True)
    employees_employees = models.ForeignKey('Employees', models.DO_NOTHING)

    def __str__(self):
        return str(self.employees_employees)

    class Meta:
        managed = False
        db_table = 'emp_accounts'
        unique_together = (('emp_accounts_id', 'employees_employees'),)


class BabakLedger(models.Model):
    babak_ledger_id = models.AutoField(primary_key=True)
    name = models.CharField(db_column='Name', max_length=45, blank=True, null=True)  # Field name made lowercase.
    debit_amount = models.FloatField(blank=True, null=True)
    desc = models.CharField(max_length=90, blank=True, null=True)
    dat = models.DateField(blank=True, null=True)
    rmb = models.FloatField(blank=True, null=True)
    rup = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'babak_ledger'


class DebRecvLedger(models.Model):

templates/employess/add_emp_fp.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">

    <div class="offset-2 col-md-8">
        <form method="post" id="empform">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-primary" id="combtn" type="submit" value="Add">
        </form>

{% include 'employess/emp_list.html' %}

</div>
</div>


{% endblock %}

templates/employess/emp_details.html
{% extends 'base.html' %}
{% block content %}

    <div class="row">
        <div class="col-sm-12" align="center">
            <h1>Stock Report</h1>



            <table class="table-responsive-sm table-bordered">
                <thead>

                <tr>
                    <th style="text-align:center; color:white;" bgcolor="#8a2be2">Emp id:</th>
                    <th style="text-align:center; color:white;" bgcolor="#8a2be2">Employee Name:</th>
                    <th style="text-align:center; color:white;" bgcolor="#8a2be2">Employee Salary:</th>
                    <th style="text-align:center; color:white;" bgcolor="#8a2be2">Amount Given</th>
                    <th style="text-align:center; color:white;" bgcolor="#8a2be2">Date</th>


                </tr>
                </thead>
                <tbody>
                {% for ss in s %}
                    {#            {% for a in ss.salesdetails_set.all %}#}
                    <tr>

                        <td>{{ ss.st_id }}</td>
                        <td>{{ ss.company_company }}</td>
                        <td>{{ ss.date }}</td>
                        <td>{{ ss.bill_no }}</td>
                        <td>{{ ss.buity_no }}</td>
                        <td>{{ ss.exp }}</td>
                        <td>{{ ss.total_bill }}</td>
                        <td>{{ ss.status }}</td>


                    </tr>

                {% endfor %}

                </tbody>

            </table>


        </div>


    </div><p></p>


{% endblock content %}

templates/employess/emp_list.html
<div class="row">
    <div class="col-md-12 mx-auto">
        <h3 align="center">All Employees</h3>

        <table class="table-responsive-sm table-bordered mx-auto">
    <thead>

      <tr>
        <th>No</th>
        <th style="text-align:center;">Employee Name</th>
        <th style="text-align:center;">Employees job title</th>
        <th style="text-align:center;">Salary</th>
        <th style="text-align:center;">Credit</th>
        <th style="text-align:center;">Debit</th>




      </tr>
    </thead>
    <tbody>
        {% for ss in e %}
      <tr>
        <td class="text-center">{{ forloop.counter }}</td>
        <td class="text-center">{{ ss.employees_name}}</td>
        <td class="text-center">{{ ss.employees_job_title }}</td>
        <td class="text-center">{{ ss.employees_salary }}</td>
        <td class="text-center">{{ ss.emp_accounts_credit }}</td>
        <td class="text-center">{{ ss.emp_accounts_debit }}</td>


{#        <a href="/defaulters/{{ ss.accounts_name }}">  &nbsp;Click for Details</a>#}


        </td>
      </tr>
        {% endfor %}

    </tbody>
  </table>
    </div>
    </div>

templates/employess/sal.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1  align="center">Pay Salaries to Employes </h1><p>
    <form id='salform' onsubmit="return false">

        <table class="table-responsive-sm table-bordered mx-auto table-info">
            <thead>
            <tr>

                <th style="text-align:center;">Salary Amount:</th>
                <th style="text-align:center;">Employee Name:</th>
                <th style="text-align:center;">Paying Method:</th>
                <th style="text-align:center;">Description</th>
                <th style="text-align:center;">Date</th>

            </thead>
            <tbody>
            <tr>


                <td>
                    <input name="amount" type="text" class="form-control form-control-sm tqty">

                </td>
                <td>
                    <input type="text" name="comn" list="company" class="form-control form-sm"/>
                    <datalist id="company">
                        {% for p in acc %}
                            <option value="{{ p.employees_name }}">{{ p.employees_name }}</option>
                        {% endfor %}
                    </datalist>


                </td>
                <td><input name="method" type="text" class="form-control form-control-sm tqty"></td>
                <td><input name="des" type="text" class="form-control form-control-sm tqty"></td>
                <td><input name="dt" type="text" class="form-control form-control-sm qty"></td>


            </tr>


            </tbody>

        </table> <!--Table Ends-->
        <center style="padding:10px;">

            <button id="sal" style="width:150px;" class="btn btn-primary">Submit</button>
        </center>
    </form>




{% endblock %}

templates/employess/saldetails.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-8 mx-auto">
        <h3 align="center">History of Salary Payments To Employees</h3>
        <table align="center" class="table-responsive-sm table-bordered mx-auto">
    <thead>
      <tr>
        <th>Ser</th>

        <th style="text-align:center;">Employee Name:</th>

                <th style="text-align:center;">Salary Amount:</th>
                <th style="text-align:center;">Method:</th>
                <th style="text-align:center;">Description</th>
                <th style="text-align:center;">Date</th>


      </tr>
    </thead>
    <tbody>
    {% for c in leg %}
  <tr>
    <td>{{ forloop.counter }}</td>

    <td>{{ c.emp_name}}</td>

      <td>{{ c.amount}}</td>
      <td>{{ c.method}}</td>
      <td>{{ c.desc}}</td>
    <td>{{ c.dat}}</td>





  </tr>
{% empty %}
  <tr>
    <td colspan="7" class="text-center bg-warning">No Salary Given</td>
  </tr>
{% endfor %}
</tbody>
</table>
{#    <h5 align="center">Total Expense: {{ total }}</h5>#}
    </div>
</div>


{% endblock content %}